name: telegram-bot
services:
  - name: bot
    git:
      repository: saruarofc/done
      branch: main
    instance_types:
      - nano
    run_command: python bot.py
    ports:
      - port: 8000
        protocol: tcp
